name: Semantic Release

on:
  push:
    branches:
      - development

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies
        run: |
            yarn install
            yarn tauri build --debug

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Create GitHub Release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: v${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body: "Release notes for ${{ github.ref }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}