name: Build, Release, deploy

on:
  push:
    branches:
      - development

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}


jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies and deploy
        run: |
          yarn install
          yarn tauri build --debug
          # Additional deployment steps if needed
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload Release Asset for msi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: "D:/a/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/msi/Sparrow-app_0.0.0_x64_en-US.msi"
          asset_name: Sparrow-app_0.0.0_x64_en-US.msi${{ github.run_number }}
          asset_content_type: application/zip
      
      - name: Upload Release Asset for nsis
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: "D:/a/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/nsis/sparrow-app_0.0.0_x64-setup.exe"
          asset_name: sparrow-app_0.0.0_x64-setup.exe${{ github.run_number }}
          asset_content_type: application/zip
