name: Semantic Release

on:
  push:
    branches:
      - development

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install dependencies
        run: yarn install

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release notes for ${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}