name: Semantic Release and File Rename

on:
  push:
    branches:
      - development

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies
        run: |
          yarn cache clean
          npm install -g pnpm
          yarn install
          yarn tauri build --debug

      - name: Run Semantic Release
        id: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Extract Version from Semantic Release
        id: extract-version
        run: |
          version=$(grep -oP 'Published file .+sparrow-app_\K\d+\.\d+\.\d+' <<< "${{ steps.semantic-release.outputs.stdout }}")
          echo "::set-output name=version::${version}"

      - name: Rename .exe file with version
        run: mv D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/nsis/sparrow-app_0.0.0_x64-setup.exe "D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/nsis/sparrow-app_${{ steps.extract-version.outputs.version }}_x64-setup.exe"

      - name: Rename .msi file with version
        run: mv D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/msi/sparrow-app_0.0.0_x64_en-US.msi "D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/msi/sparrow-app_${{ steps.extract-version.outputs.version }}_x64_en-US.msi"

      - name: Commit and Push Version Change
        run: |
          git config --local user.email "pratik.shinde@techdome.net.in"
          git config --local user.name "pratikshinde590"
          git add -A
          git commit -m "chore(release): version ${{ steps.extract-version.outputs.version }}"
          git push origin development
        env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
            
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ steps.semantic-release.outputs.upload_url }}
          asset_path: D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/nsis/sparrow-app_${{ steps.extract-version.outputs.version }}_x64-setup.exe
          asset_name: sparrow-app_${{ steps.extract-version.outputs.version }}_x64-setup.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ steps.semantic-release.outputs.upload_url }}
          asset_path: D:/a/sparrow-ap/sparrow-ap/src-tauri/target/debug/bundle/msi/sparrow-app_${{ steps.extract-version.outputs.version }}_x64_en-US.msi
          asset_name: sparrow-app_${{ steps.extract-version.outputs.version }}_x64_en-US.msi
          asset_content_type: application/octet-stream
